/**
 * Virtual Mandir seed (module doc §14 T3). Idempotent and create-only: rows have fixed ids and
 * existing rows are never overwritten, so admin edits and the dev-user's spent coins survive.
 * Placeholder media is (re)uploaded every run — keys are seed-owned and content is deterministic.
 */
import { REMOTE_CONFIG_FLAG_KEY } from '@mandir/shared-types';

import { DEV_USERS } from '../../src/core/auth/dev-users.js';
import type { StorageService } from '../../src/core/storage/storage.service.js';
import type { Prisma, PrismaClient } from '../../src/generated/prisma/client.js';
import { seedId } from './ids.js';
import {
  COIN_PACKS,
  DEFAULT_THEME,
  DEITIES,
  DEV_USER_START_COINS,
  MANDIR_FLAGS,
  MANDIR_REMOTE_CONFIG,
  OFFERINGS,
  PLACEHOLDER_AARTI_SECONDS,
  REWARD_RULES,
  type SeedDeity,
} from './mandir-data.js';
import {
  aartiTone,
  deityImage,
  type ImageVariant,
  lyricsTimeline,
  offeringSprite,
  themeFrame,
} from './placeholder-media.js';

const PLACEHOLDER_LICENSE = 'PLACEHOLDER generated by seed — replace with a licensed image before launch';

export async function seedMandir(prisma: PrismaClient, storage: StorageService): Promise<void> {
  const deityIds = new Map<string, string>();
  for (const [index, deity] of DEITIES.entries()) {
    deityIds.set(deity.slug, await seedDeity(prisma, storage, deity, index));
  }
  await seedOfferings(prisma, storage, deityIds);
  await seedCoinPacks(prisma);
  await seedRewardRules(prisma);
  await seedFlags(prisma);
  await seedTheme(prisma, storage);
  await seedDevWallet(prisma);
}

/** Temple + deity + one PUBLIC official image (set as default) + one default aarti. */
async function seedDeity(
  prisma: PrismaClient,
  storage: StorageService,
  d: SeedDeity,
  sortOrder: number,
): Promise<string> {
  const templeId = seedId(`temple:${d.slug}`);
  const deityId = seedId(`deity:${d.slug}`);
  const imageId = seedId(`image:${d.slug}:official-1`);
  const aartiId = seedId(`aarti:${d.slug}:default`);

  const { photographyRestricted = false, ...temple } = d.temple;
  await prisma.temple.upsert({
    where: { id: templeId },
    update: {},
    create: { id: templeId, ...temple, photographyRestricted, isVerified: true },
  });

  await prisma.deity.upsert({
    where: { id: deityId },
    update: {},
    create: { id: deityId, slug: d.slug, nameHi: d.nameHi, nameEn: d.nameEn, weekday: d.weekday, sortOrder },
  });

  // Official placeholder image: original + WebP variants in media-public.
  const base = `official/${d.slug}/${imageId}`;
  const img = await deityImage(d.nameEn, d.colors);
  const variantKeys = Object.fromEntries(
    Object.keys(img.variants).map((v) => [v, `${base}/${v}.webp`]),
  ) as Record<ImageVariant, string>;
  await Promise.all([
    storage.put(`${base}/original.png`, img.original, 'image/png'),
    ...Object.entries(img.variants).map(([v, buf]) =>
      storage.put(variantKeys[v as ImageVariant], buf, 'image/webp'),
    ),
  ]);
  await prisma.deityImage.upsert({
    where: { id: imageId },
    update: {},
    create: {
      id: imageId,
      deityId,
      templeId,
      source: 'OFFICIAL',
      status: 'PUBLIC',
      objectKey: `${base}/original.png`,
      variants: variantKeys,
      width: img.width,
      height: img.height,
      anchorX: 0.5,
      anchorY: 0.35,
      showCredit: false,
      licenseInfo: PLACEHOLDER_LICENSE,
    },
  });
  // Only fill an empty default — an admin may have picked another image.
  await prisma.deity.updateMany({ where: { id: deityId, defaultImageId: null }, data: { defaultImageId: imageId } });

  // Default aarti: placeholder tone + lyrics timeline.
  const audioKey = `audio/aarti/${d.slug}/v1.wav`;
  const lyricsKey = `lyrics/aarti/${d.slug}/v1.json`;
  await Promise.all([
    storage.put(audioKey, aartiTone(PLACEHOLDER_AARTI_SECONDS, sortOrder), 'audio/wav'),
    storage.put(
      lyricsKey,
      JSON.stringify(lyricsTimeline(d.aarti.titleHi, PLACEHOLDER_AARTI_SECONDS)),
      'application/json; charset=utf-8',
    ),
  ]);
  await prisma.aarti.upsert({
    where: { id: aartiId },
    update: {},
    create: {
      id: aartiId,
      deityId,
      titleHi: d.aarti.titleHi,
      titleEn: d.aarti.titleEn,
      audioKey,
      lyricsKey,
      durationSec: PLACEHOLDER_AARTI_SECONDS,
      version: 1,
      isDefault: true,
      licenseInfo: 'PLACEHOLDER tone generated by seed — replace with a licensed recording before launch',
    },
  });

  return deityId;
}

async function seedOfferings(
  prisma: PrismaClient,
  storage: StorageService,
  deityIds: Map<string, string>,
): Promise<void> {
  for (const [sortOrder, o] of OFFERINGS.entries()) {
    const id = seedId(`offering:${o.key}`);
    const iconKey = `official/offerings/${o.key}/icon.webp`;
    const spriteKey = `official/offerings/${o.key}/sprite.webp`;
    await Promise.all([
      storage.put(iconKey, await offeringSprite(o.color, 128), 'image/webp'),
      storage.put(spriteKey, await offeringSprite(o.color, 256), 'image/webp'),
    ]);
    // iconUrl/spriteUrl hold object keys; the API resolves them to CDN URLs (module doc §5 notes).
    await prisma.offeringItem.upsert({
      where: { id },
      update: {},
      create: {
        id,
        kind: o.kind,
        nameHi: o.nameHi,
        nameEn: o.nameEn,
        iconUrl: iconKey,
        spriteUrl: spriteKey,
        animationKey: o.animationKey,
        particleCount: o.particleCount,
        coinCost: o.coinCost,
        sortOrder,
      },
    });
    if (o.deities.length > 0) {
      await prisma.offeringItemDeity.createMany({
        data: o.deities.map((slug) => {
          const deityId = deityIds.get(slug);
          if (!deityId) throw new Error(`Offering "${o.key}" references unknown deity "${slug}"`);
          return { offeringItemId: id, deityId };
        }),
        skipDuplicates: true,
      });
    }
  }
}

async function seedCoinPacks(prisma: PrismaClient): Promise<void> {
  for (const pack of COIN_PACKS) {
    const id = seedId(`coin-pack:${pack.coins}`);
    await prisma.coinPack.upsert({ where: { id }, update: {}, create: { id, ...pack } });
  }
}

async function seedRewardRules(prisma: PrismaClient): Promise<void> {
  for (const rule of REWARD_RULES) {
    await prisma.rewardRule.upsert({
      where: { key: rule.key },
      update: {},
      create: { id: seedId(`reward-rule:${rule.key}`), ...rule },
    });
  }
}

async function seedFlags(prisma: PrismaClient): Promise<void> {
  for (const flag of MANDIR_FLAGS) {
    await prisma.featureFlag.upsert({ where: { key: flag.key }, update: {}, create: flag });
  }

  // Add this module's remote config keys where missing; never overwrite admin-edited values.
  const row = await prisma.featureFlag.findUniqueOrThrow({ where: { key: REMOTE_CONFIG_FLAG_KEY } });
  const current = (row.payload ?? {}) as Prisma.JsonObject;
  const missing = Object.entries(MANDIR_REMOTE_CONFIG).filter(([k]) => !(k in current));
  if (missing.length > 0) {
    await prisma.featureFlag.update({
      where: { key: REMOTE_CONFIG_FLAG_KEY },
      data: { payload: { ...current, ...Object.fromEntries(missing) } },
    });
  }
}

async function seedTheme(prisma: PrismaClient, storage: StorageService): Promise<void> {
  const frameKey = `themes/${DEFAULT_THEME.key}/frame.webp`;
  await storage.put(frameKey, await themeFrame(), 'image/webp');
  await prisma.theme.upsert({
    where: { key: DEFAULT_THEME.key },
    update: {},
    create: {
      id: seedId(`theme:${DEFAULT_THEME.key}`),
      key: DEFAULT_THEME.key,
      frameKey,
      colors: DEFAULT_THEME.colors,
      isActive: true,
    },
  });
}

/** dev-user starts with 50 coins via a ledger entry, so wallet and history stay consistent (§5 rules). */
async function seedDevWallet(prisma: PrismaClient): Promise<void> {
  const userId = DEV_USERS['dev-user'].id;
  await prisma.$transaction(async (tx) => {
    if (await tx.coinWallet.findUnique({ where: { userId } })) return;
    await tx.coinWallet.create({ data: { userId, balance: DEV_USER_START_COINS } });
    await tx.coinTransaction.create({
      data: {
        id: seedId('coin-txn:dev-user-start'),
        userId,
        amount: DEV_USER_START_COINS,
        balanceAfter: DEV_USER_START_COINS,
        reason: 'ADMIN_ADJUST',
        refType: 'admin',
        refId: 'seed',
      },
    });
  });
}
